# Generated by Django 3.1.5 on 2021-01-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=250)),
                ('keywords', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('image', models.ImageField(upload_to='images/service')),
                ('describe', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
