# Generated by Django 3.1.5 on 2021-01-30 11:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='describe',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
