# Generated by Django 3.1.5 on 2021-01-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210130_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='describe',
        ),
    ]
