# Generated by Django 3.1.5 on 2021-01-30 11:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_service_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='describe',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
