# Generated by Django 3.1.5 on 2021-01-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
