# Generated by Django 3.1.5 on 2021-02-02 12:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
