# Generated by Django 3.1.5 on 2021-02-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_servicepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepicture',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
            preserve_default=False,
        ),
    ]
