# Generated by Django 3.1.5 on 2021-02-06 10:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_servicepicture_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_tk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en_us',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_tk',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='create_at',
            field=models.DateField(auto_now_add=True, verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='images/service', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='update_at',
            field=models.DateField(auto_now=True, verbose_name='update_at'),
        ),
        migrations.AlterField(
            model_name='servicepicture',
            name='image',
            field=models.ImageField(upload_to='images/service', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='servicepicture',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
