# Generated by Django 3.1.5 on 2021-02-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='images/blog'),
            preserve_default=False,
        ),
    ]
