# Generated by Django 3.1.5 on 2021-02-05 05:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpicture',
            name='image',
            field=models.ImageField(upload_to='images/aboutus', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='aboutpicture',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='images/aboutus', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(upload_to='image/achievement', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='header',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='images/blog', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='numbercomment',
            field=models.IntegerField(verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update_at'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='image',
            field=models.ImageField(upload_to='image/clients', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=300, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=500, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update_at'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='aboutus'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='company',
            field=models.CharField(max_length=50, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='keywords',
            field=models.CharField(max_length=255, verbose_name='keyword'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='references',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='references'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smtpemail',
            field=models.CharField(blank=True, max_length=50, verbose_name='smtpemail'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smtppassword',
            field=models.CharField(blank=True, max_length=50, verbose_name='smtppassword'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smtpport',
            field=models.CharField(blank=True, max_length=50, verbose_name='smtpport'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smtpserver',
            field=models.CharField(blank=True, max_length=50, verbose_name='smtpserver'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='status',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update_at'),
        ),
    ]
