# Generated by Django 3.1.5 on 2021-02-05 06:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210205_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_en_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_tk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en_us',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_tk',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_tr',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
    ]
