# Generated by Django 3.1.5 on 2021-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210206_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/slider', verbose_name='image')),
                ('header', models.CharField(max_length=50, verbose_name='header')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
