# Generated by Django 3.1.5 on 2021-02-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description_en_us',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_tk',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='header_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='header'),
        ),
        migrations.AddField(
            model_name='slider',
            name='header_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='header'),
        ),
        migrations.AddField(
            model_name='slider',
            name='header_tk',
            field=models.CharField(max_length=50, null=True, verbose_name='header'),
        ),
        migrations.AddField(
            model_name='slider',
            name='header_tr',
            field=models.CharField(max_length=50, null=True, verbose_name='header'),
        ),
    ]
